import React, { useState, useEffect, useCallback } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Calendar, Clock, MapPin, RefreshCw, Route } from 'lucide-react';
import { format, isToday, isTomorrow, isYesterday, addDays, startOfWeek, endOfWeek } from 'date-fns';
import type { User, Customer } from '@/lib/firebase-types';
import type { AutoGeneratedSchedule } from '@/lib/auto-schedule-service';
import { createAutoScheduleGenerator } from '@/lib/auto-schedule-service';

interface ScheduleViewProps {
  crewId: string;
  crewMembers: User[];
  customers: Customer[];
  companyId: string;
  onViewRoute?: (schedule: AutoGeneratedSchedule) => void;
  onRefreshSchedules?: () => void;
}

const getDateLabel = (date: Date): string => {
  if (isToday(date)) return 'Today';
  if (isTomorrow(date)) return 'Tomorrow';
  if (isYesterday(date)) return 'Yesterday';
  return format(date, 'EEEE, MMM d');
};

const getWeekRange = (date: Date) => {
  const start = startOfWeek(date, { weekStartsOn: 1 }); // Monday start
  const end = endOfWeek(date, { weekStartsOn: 1 });
  return { start, end };
};

export function ScheduleView({
  crewId,
  crewMembers,
  customers: _customers,
  companyId,
  onViewRoute,
  onRefreshSchedules: _onRefreshSchedules
}: ScheduleViewProps) {
  const [currentDate, setCurrentDate] = useState(new Date());
  const [viewMode, setViewMode] = useState<'week' | 'day'>('week');
  const [schedules, setSchedules] = useState<AutoGeneratedSchedule[]>([]);
  const [isLoading, setIsLoading] = useState(false);

  const { start: weekStart, end: weekEnd } = getWeekRange(currentDate);

  // Generate schedules for the current week
  const generateSchedules = useCallback(async () => {
    setIsLoading(true);
    try {
      const generator = createAutoScheduleGenerator(companyId);
      await generator.initialize();

      const options = {
        startDate: viewMode === 'week' ? weekStart : currentDate,
        endDate: viewMode === 'week' ? weekEnd : currentDate,
        includeWeekends: true,
        maxCustomersPerDay: 12,
        serviceBufferMinutes: 15,
      };

      const generatedSchedules = await generator.generateSchedules(options);

      // Filter schedules for this crew
      const crewSchedules = generatedSchedules.filter((schedule: AutoGeneratedSchedule) => schedule.crewId === crewId);
      setSchedules(crewSchedules);
    } catch (error) {
      console.error('Error generating schedules:', error);
    } finally {
      setIsLoading(false);
    }
  }, [companyId, crewId, currentDate, viewMode, weekStart, weekEnd]);

  useEffect(() => {
    generateSchedules();
  }, [generateSchedules]);

  const navigateWeek = (direction: 'prev' | 'next') => {
    setCurrentDate(prev => addDays(prev, direction === 'next' ? 7 : -7));
  };

  const navigateDay = (direction: 'prev' | 'next') => {
    setCurrentDate(prev => addDays(prev, direction === 'next' ? 1 : -1));
  };

  const getDaySchedules = (date: Date): AutoGeneratedSchedule[] => {
    return schedules.filter(schedule => 
      format(schedule.date, 'yyyy-MM-dd') === format(date, 'yyyy-MM-dd')
    );
  };

  const renderDayView = () => (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-4">
          <Button
            variant="outline"
            size="sm"
            onClick={() => navigateDay('prev')}
          >
            ← Previous
          </Button>
          <h2 className="text-xl font-semibold">
            {getDateLabel(currentDate)}
          </h2>
          <Button
            variant="outline"
            size="sm"
            onClick={() => navigateDay('next')}
          >
            Next →
          </Button>
        </div>
        <Button 
          onClick={generateSchedules} 
          size="sm"
          disabled={isLoading}
        >
          <RefreshCw className={`w-4 h-4 mr-2 ${isLoading ? 'animate-spin' : ''}`} />
          Refresh
        </Button>
      </div>

      {isLoading ? (
        <Card>
          <CardContent className="p-8 text-center">
            <RefreshCw className="w-12 h-12 mx-auto text-muted-foreground mb-4 animate-spin" />
            <h3 className="text-lg font-medium mb-2">Generating schedules...</h3>
            <p className="text-muted-foreground">
              Analyzing customer preferences and crew availability
            </p>
          </CardContent>
        </Card>
      ) : schedules.length === 0 ? (
        <Card>
          <CardContent className="p-8 text-center">
            <Calendar className="w-12 h-12 mx-auto text-muted-foreground mb-4" />
            <h3 className="text-lg font-medium mb-2">No schedules for this day</h3>
            <p className="text-muted-foreground mb-4">
              No customers need service on this day or crew is not available
            </p>
            <Button onClick={generateSchedules}>
              <RefreshCw className="w-4 h-4 mr-2" />
              Regenerate Schedules
            </Button>
          </CardContent>
        </Card>
      ) : (
        <div className="space-y-4">
          {schedules.map((schedule) => (
            <Card key={`${schedule.crewId}-${format(schedule.date, 'yyyy-MM-dd')}`} className="hover:shadow-md transition-shadow">
              <CardHeader>
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <Clock className="w-5 h-5 text-muted-foreground" />
                    <div>
                      <CardTitle className="text-lg">
                        {schedule.estimatedStartTime} - {schedule.estimatedEndTime}
                      </CardTitle>
                      <p className="text-sm text-muted-foreground">
                        {schedule.customers.length} customers • {schedule.totalDistance.toFixed(1)} km
                      </p>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    <Badge className="bg-green-100 text-green-800">
                      Auto-Generated
                    </Badge>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => onViewRoute?.(schedule)}
                    >
                      <Route className="w-4 h-4 mr-2" />
                      View Route
                    </Button>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <div className="space-y-3">
                  {schedule.customers.map((customer, index) => (
                    <div
                      key={customer.id}
                      className="flex items-center justify-between p-3 bg-muted/50 rounded-lg"
                    >
                      <div className="flex items-center gap-3">
                        <MapPin className="w-4 h-4 text-muted-foreground" />
                        <div>
                          <p className="font-medium">
                            {customer.name}
                          </p>
                          <p className="text-sm text-muted-foreground">
                            {customer.address}
                          </p>
                        </div>
                      </div>
                      <div className="flex items-center gap-2">
                        <Badge variant="outline">
                          Stop {index + 1}
                        </Badge>
                        <Badge variant="outline">
                          {customer.services.length} services
                        </Badge>
                      </div>
                    </div>
                  ))}
                </div>
                <div className="mt-4 p-3 bg-blue-50 rounded-lg">
                  <p className="text-sm text-blue-800">
                    <strong>Route Info:</strong> {schedule.optimizedRoute.length} stops, 
                    {schedule.totalDistance.toFixed(1)} km total distance
                  </p>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );

  const renderWeekView = () => (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-4">
          <Button
            variant="outline"
            size="sm"
            onClick={() => navigateWeek('prev')}
          >
            ← Previous Week
          </Button>
          <h2 className="text-xl font-semibold">
            {format(weekStart, 'MMM d')} - {format(weekEnd, 'MMM d, yyyy')}
          </h2>
          <Button
            variant="outline"
            size="sm"
            onClick={() => navigateWeek('next')}
          >
            Next Week →
          </Button>
        </div>
        <Button 
          onClick={generateSchedules} 
          size="sm"
          disabled={isLoading}
        >
          <RefreshCw className={`w-4 h-4 mr-2 ${isLoading ? 'animate-spin' : ''}`} />
          Refresh
        </Button>
      </div>

      <div className="grid grid-cols-7 gap-4">
        {Array.from({ length: 7 }, (_, i) => {
          const date = addDays(weekStart, i);
          const daySchedules = getDaySchedules(date);
          
          return (
            <Card key={i} className="min-h-[200px]">
              <CardHeader className="pb-2">
                <CardTitle className="text-sm">
                  {format(date, 'EEE')}
                </CardTitle>
                <p className="text-xs text-muted-foreground">
                  {format(date, 'MMM d')}
                </p>
                {isToday(date) && (
                  <Badge className="bg-blue-100 text-blue-800 text-xs">
                    Today
                  </Badge>
                )}
              </CardHeader>
              <CardContent className="pt-0">
                {daySchedules.length === 0 ? (
                  <p className="text-xs text-muted-foreground text-center mt-4">
                    No schedules
                  </p>
                ) : (
                  <div className="space-y-2">
                    {daySchedules.map((schedule) => (
                      <div
                        key={`${schedule.crewId}-${format(schedule.date, 'yyyy-MM-dd')}`}
                        className="p-2 bg-muted/50 rounded text-xs cursor-pointer hover:bg-muted transition-colors"
                        onClick={() => onViewRoute?.(schedule)}
                      >
                        <div className="flex items-center justify-between mb-1">
                          <span className="font-medium">
                            {schedule.estimatedStartTime}
                          </span>
                          <Badge className="bg-green-100 text-green-800">
                            Auto
                          </Badge>
                        </div>
                        <p className="text-muted-foreground">
                          {schedule.customers.length} customers
                        </p>
                      </div>
                    ))}
                  </div>
                )}
              </CardContent>
            </Card>
          );
        })}
      </div>
    </div>
  );

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold">Auto-Generated Schedule</h1>
          <p className="text-muted-foreground">
            AI-powered scheduling for {crewMembers[0]?.crewName || 'Crew'}
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Button
            variant={viewMode === 'day' ? 'default' : 'outline'}
            size="sm"
            onClick={() => setViewMode('day')}
          >
            Day
          </Button>
          <Button
            variant={viewMode === 'week' ? 'default' : 'outline'}
            size="sm"
            onClick={() => setViewMode('week')}
          >
            Week
          </Button>
        </div>
      </div>

      {viewMode === 'day' ? renderDayView() : renderWeekView()}
    </div>
  );
} 